package com.avik.microservices.catalogue_service.mapper;

import com.avik.microservices.catalogue_service.dto.ProductRequestDto;
import com.avik.microservices.catalogue_service.dto.ProductResponseDto;
import com.avik.microservices.catalogue_service.entity.Product;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.List;

@Mapper(componentModel = "spring") //It tells MapStruct to generate the mapper as a Spring-managed bean so it can be injected using dependency injection instead of being created manually.
public interface ProductMapper {

    @Mapping(target = "category", ignore = true) //This annotation is used to specify that the id field should be ignored during the mapping process. This is useful when creating a new Product entity from a ProductRequestDto, as the id will typically be generated by the database and should not be set manually.
    Product toEntity(ProductRequestDto productRequestDto);

    @Mapping(source = "category.id", target = "categoryId") //This annotation is used to specify that the categoryId field in the ProductResponseDto should be mapped from the id field of the category property in the Product entity. This allows us to include the category ID in the response DTO without needing to include the entire Category object.
    ProductResponseDto toDto(Product product);


    List<ProductResponseDto> toDtoList(List<Product> products);

}
