spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projects
    username: postgres
    password: voldemort

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  profile: DEV
